---
language: android
android:
  components:
    - build-tools-26.0.2
    - android-27
jdk: oraclejdk8
before_install:
  - nvm install 8
install:
  - yarn install --frozen-lockfile
  - yarn cordova prepare
script: yarn cordova build android
